// <auto-generated />
using System;
using Dating_WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dating_WebAPI.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201211023851_AddTables")]
    partial class AddTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Dating_WebAPI.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FavorId")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("SexualId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("FavorId");

                    b.HasIndex("SexualId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dating_WebAPI.Entities.Favor", b =>
                {
                    b.Property<int>("FavorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FavorType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FavorId");

                    b.ToTable("Favor");
                });

            modelBuilder.Entity("Dating_WebAPI.Entities.Sexual", b =>
                {
                    b.Property<int>("SexualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("SexualType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SexualId");

                    b.ToTable("Sexual");
                });

            modelBuilder.Entity("Dating_WebAPI.Entities.AppUser", b =>
                {
                    b.HasOne("Dating_WebAPI.Entities.Favor", "Favor")
                        .WithMany("AppUsers")
                        .HasForeignKey("FavorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dating_WebAPI.Entities.Sexual", "Sexual")
                        .WithMany("AppUsers")
                        .HasForeignKey("SexualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Favor");

                    b.Navigation("Sexual");
                });

            modelBuilder.Entity("Dating_WebAPI.Entities.Favor", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("Dating_WebAPI.Entities.Sexual", b =>
                {
                    b.Navigation("AppUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
